update core-rest-pipeline version
Azure/autorest.typescript pull request #2174
Opened 2023-12-26 02:00 UTC by kazrael2119

2024-01-18 07:50 UTC, qiaozha requested changes
as core-rest-pipeline latest beta version has some issues.

2024-02-02 07:45 UTC, MaryGao commented on packages/autorest.typescript/test/version-tolerance/generated/rlc-updated/package.json
> -    "@azure-rest/core-client": "1.0.0-beta.9",
why we have beta? could you check?

2024-02-02 07:47 UTC, MaryGao commented on packages/typespec-ts/test/modularIntegration/customClientRequestId.spec.ts
> +  }).timeout(36000);
change timeout in package.json not signle ut

2024-02-02 08:33 UTC, MaryGao approved these changes
LGTM

2024-02-02 08:43 UTC, lirenhe approved these changes

2024-02-02 08:47 UTC, qiaozha approved these changes

2024-02-02 09:31 UTC, merged