Update the changelog
Azure/autorest.typescript pull request #2755
Opened 2024-08-15 10:22 UTC by MaryGao

2024-08-15 10:23 UTC, MaryGao commented on packages/autorest.typescript/CHANGELOG.md
> +  - Bump typescript version to ~5.5.3, please refer to [#2646](https://github.com/Azure/autorest.typescript/pull/2646);
it seems the format is correct: https://github.com/Azure/autorest.typescript/blob/1d1acc18fb4d23174f1dfea41b0dcc43420847ac/packages/autorest.typescript/CHANGELOG.md
![image](https://github.com/user-attachments/assets/99c997a6-d8a5-4502-8dec-c9271cd013a2)

2024-08-15 11:13 UTC, qiaozha commented
Can you check if we can wait for this PR to be merged https://github.com/Azure/autorest.typescript/pull/2751

2024-08-16 01:45 UTC, lirenhe commented on packages/autorest.typescript/CHANGELOG.md
> +- [Feature] Upgrade compiler to v0.59. Please refer to [#2741](https://github.com/Azure/autorest.typescript/pull/2741).
TypeSpec compiler to 0.59

2024-08-16 01:51 UTC, lirenhe approved these changes
One wording issue,  other part looks good.

2024-08-16 02:55 UTC, qiaozha commented on packages/rlc-common/CHANGELOG.md
> +## 6.0.26 (2024-08-15)
6.0.26 for rlc common ?

2024-08-16 02:56 UTC, qiaozha commented on packages/typespec-ts/CHANGELOG.md
> +## 6.0.26 (2024-08-15)
same here.

2024-08-16 02:56 UTC, qiaozha requested changes
please don't copy the autorest.typescript change log into rlc-common or typespec-ts folder

2024-08-16 05:57 UTC, qiaozha approved these changes

2024-08-16 08:45 UTC, merged