Unify the typespec options to kebab-case style
Azure/autorest.typescript pull request #2960
Opened 2024-12-23 05:31 UTC by v-jiaodi

fix issue #2955

2025-01-08 07:35 UTC, qiaozha commented
We need to update the docs and tspconfig.yaml in the spec repo and @wanlwanl please also be aware of the impact to automation related task.

2025-01-22 03:17 UTC, MaryGao commented
Pls update all doc to kebab-case style in autorest.typescript repo including README and CONTRIBUTION doc.

2025-01-26 07:20 UTC, MaryGao commented on packages/typespec-ts/README.md
> +    package-details:
Please don't merge this pr, we need to a way to mark the old option pattern as deprecation.

2025-01-26 07:21 UTC, MaryGao requested changes
Need to improve with deprecation messages.

2025-02-18 03:33 UTC, MaryGao commented on packages/typespec-test/test/NetworkAnalytics.Management/tspconfig.yaml
> +    typespec-title-map:
pls include change in ut

2025-02-25 01:40 UTC, wanlwanl commented
This PR impact the sdk automation for each generation, please ping me in teams before this PR get merged, thanks

2025-02-26 05:17 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +      kababCaseOption: caseOption.kababCaseOption,
```suggestion
      kebabCaseOption: caseOption.kebabCaseOption,
```

2025-02-26 05:20 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +    emitterOptions["multi-client"] || emitterOptions.multiClient;
why some is || and some is ??

2025-02-26 05:33 UTC, MaryGao commented on packages/typespec-ts/src/lib.ts
> +        default: paramMessage`The option - ${"camalCaseOption"} is deprecated and please use this kebab-case one - ${"kababCaseOption"}.`
kababCaseOption?

2025-02-26 05:39 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  if (emitterOptions.multiClient !== undefined) {
reportAllCamelOptionDiagnostics

2025-02-26 05:40 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  if (emitterOptions.enableOperationGroup !== undefined) {
in that helper

2025-02-26 05:40 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  if (emitterOptions.enableModelNamespace !== undefined) {
+1

2025-02-26 05:43 UTC, MaryGao commented on packages/typespec-ts/src/index.ts
> +        context.options["experimental-extensible-enums"];
kebab-case is preferred

2025-02-26 05:44 UTC, MaryGao commented on packages/typespec-ts/src/lib.ts
> +// export interface EmitterOptions extends RLCOptions {
removed it

2025-02-26 05:48 UTC, MaryGao commented on packages/typespec-ts/src/lib.ts
> +export const RLCOptionsOldSchema: JSONSchemaType<RLCOptions> = {
_RLCOptionsSchema and remove export

2025-02-27 06:38 UTC, MaryGao commented on packages/typespec-ts/src/lib.ts
> +  [key: string]: any;
remove this, this is not allowed!

2025-02-27 06:41 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  const defaultDetial = {
=》 defaultDetail

2025-02-27 06:42 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  if (emitterOptions["package-details"] !== undefined) {
kebab-case has higher priority than camelCase

2025-02-27 06:47 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +    emitterOptions["multi-client"] || emitterOptions.multiClient;
all should be `??`.

2025-02-27 06:49 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +  }
you could simplify the function with
```ts
if (emitterOptions["package-details"] !== undefined) {
   return buildPackageDetails(program, emitterOptions, "package-details");
}
return  buildPackageDetails(program, emitterOptions, "packageDetails");

```

2025-02-27 06:50 UTC, MaryGao commented on packages/typespec-ts/src/transform/transfromRLCOptions.ts
> +      : emitterOptions["credential-key-header-name"] ||
should be ??

2025-02-27 06:58 UTC, MaryGao commented on packages/typespec-ts/src/index.ts
> +          context.options["experimental-extensible-enums"] ||
??

2025-02-27 06:59 UTC, MaryGao commented on packages/typespec-ts/src/lib.ts
> +  [key: string]: any;
no this.

2025-02-28 03:12 UTC, MaryGao approved these changes

2025-02-28 05:54 UTC, qiaozha approved these changes

2025-02-28 10:44 UTC, merged